### ISSUE TITLE
How do I download your plugin files?

### ISSUE THREAD

**Issue by net21u** [LOOF-sys/Themidie2#1]
Only source code published on the release page.
How do I download your plugin files?

**Comment by LOOF-sys** [comment]
I left this project for a little while now but ill fix it later today and get the download posted

**Comment by whnam87** [comment]
> I left this project for a little while now but ill fix it later today and get the download posted

Highly appreciate your reply and fix. I look forward to it. You will be my savior bro. Really thanks.

**Comment by net21u** [comment]
> I left this project for a little while now but ill fix it later today and get the download posted

Highly appreciate your reply and fix. I look forward to it. You will be my savior bro. Really thanks.

**Comment by LOOF-sys** [comment]
consider using https://github.com/ergrelet/unlicense/tree/main to deobfuscate the Themida obfuscation for static analysis, this will be fixed for runtime-analysis soon

**Comment by net21u** [comment]
> consider using https://github.com/ergrelet/unlicense/tree/main to deobfuscate the Themida obfuscation for static analysis, this will be fixed for runtime-analysis soon

Thanks for letting me know about this great tool.
